GET http://127.0.0.1:5001/portfolio-xuan-boone/us-central1/api 
###
POST http://127.0.0.1:5001/portfolio-xuan-boone/us-central1/api 
Content-Type: application/json

{
    "name": "one",
    "lastname":"two"
}